module.exports = [
  {
    id: 39,
    name: "Mytheria",
    state: "applications_open",
    ido_starts_at: "2021-11-16T13:00:00.000Z",
    min_allocation: null,
    max_allocation: null,
    total_raise: 250000.0,
    cover_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1635936981/projects/mytheria/mytheria-card.jpg",
    logo_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1634914586/projects/mytheria/mytheria-logo.png",
    website_url: "https://mytheria.io/",
    twitter_handle: "@Mytheria_MYRA",
    telegram_handle: "MytheriaGlobal",
    twitter_url: "https://twitter.com/@Mytheria_MYRA",
    telegram_url: "https://t.me/MytheriaGlobal",
    medium_url: "",
    linkedin_url: "",
    discord_url: "",
    github_url: "",
    founded_at: "2021-10-21",
    whitepaper_url:
      "https://v2.mytheria.io/files/Mytheria-Clash-of-Pantheons.pdf",
    description:
      "## Highlights \r\n* Mytheria is a world where Gods from different cultures combat for honor and glory\r\n* It is the first NFT card game that combines play-to-earn and create-to-earn features\r\n* The team has raised $2M in private funding from top-tier VCs\r\n\r\n## Product \r\n### A mythical world with hundreds of characters to choose from\r\nThe game takes place in a world where gods from different cultures combat for honor and glory. Users choose from hundreds of different characters and artifacts to build a deck of cards in order to win battles against other players. ",
    legal_name: "",
    ethereum: false,
    bsc: true,
    polygon: false,
    application_form_url: null,
    kyc_form_url: "",
    published_at: "2021-10-27T15:10:48.839Z",
    applications_opened_at: "2021-11-01T14:33:45.638Z",
    applications_closed_at: null,
    kyc_opened_at: null,
    kyc_closed_at: null,
    submitted_to_kyc_at: null,
    submitted_to_lottery_at: null,
    contracts_deployed_at: null,
    created_at: "2021-10-21T13:12:43.753Z",
    updated_at: "2021-11-03T10:57:47.402Z",
    permitted_events: ["close_applications"],
    permitted_states: ["applications_closed"],
    slug: "mytheria",
    short_description: "The first Create to Earn NFT blockchain game!",
    ido_ends_at: null,
    ido_distributed_at: null,
    prospect_usd_token_price: 0.135,
    prospect_initial_market_cap: null,
    prospect_initial_token_circulation: null,
    token_symbol: "MYRA",
    ido_readiness_state: "applications_open",
    pool_contracts_available: false,
    pool_contract_address: "0x40FD21F9949C2DC17F74D422d34699339615cd41",
    pool_chain: "",
    finalized: false,
    applications_open_at: "2021-11-01T15:00:00.000Z",
    applications_close_at: "2021-11-09T14:00:00.000Z",
    pool_slug: "",
    pool_progress: 0,
    main_pool_id: null,
    pool_token_to: "",
    // pool_token_address: "0x2Ec6407504abFe503347e38D5a298D615DBBC0DD",
  },

  {
    id: 187,
    name: "Orion Money",
    state: "published",
    ido_starts_at: "2021-09-29T13:00:00.000Z",
    min_allocation: 0.0,
    max_allocation: 0.0,
    total_raise: 400000.0,
    cover_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1632350216/projects/orion-money/orion-cover.png",
    logo_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1631654327/projects/orion-money/orion-logo.jpg",
    website_url: "https://orion.money/",
    twitter_handle: "@orion_money",
    telegram_handle: "Orion_Money",
    twitter_url: "https://twitter.com/@orion_money",
    telegram_url: "https://t.me/Orion_Money",
    medium_url: "",
    linkedin_url: "",
    discord_url: "",
    github_url: "",
    founded_at: "2021-09-21",
    whitepaper_url:
      "https://orion-money.medium.com/orion-money-litepaper-release-7e98bb3acb6f",
    description:
      "## Highlights\r\n* Orion Money is a service developed to be a place where stablecoin holders can get a safe and secure yield of 20-25% APY in DeFi.\r\n* Orion Money brings high yields from other chains such as Terra to users on Ethereum through an easy decentralized application.\r\n* Orion Money managed to Raise $4.2 million Between seed and community rounds.\r\n\r\n## Product \r\n### Orion Money is a product that provides fixed 13.5% APY on USDT, USDC, DAI, BUSD, as well as 16.5% APY on wUST. \r\nThere are plans to increase this APY to 20-25% in the future after TGE. Additionally, users can make simple deposits, and Orion Money has passed three smart contract audits with amazing results while also managing to provide two insurance plans.",
    legal_name: "",
    ethereum: true,
    bsc: false,
    polygon: false,
    application_form_url: null,
    kyc_form_url: "",
    published_at: "2021-09-20T23:06:51.346Z",
    applications_opened_at: null,
    applications_closed_at: null,
    kyc_opened_at: null,
    kyc_closed_at: null,
    submitted_to_kyc_at: null,
    submitted_to_lottery_at: null,
    contracts_deployed_at: null,
    created_at: "2021-09-20T22:41:59.224Z",
    updated_at: "2021-10-27T20:38:26.413Z",
    permitted_events: ["unpublish"],
    permitted_states: ["draft"],
    slug: "orion-money",
    short_description: "Cross-chain stablecoin bank",
    ido_ends_at: "2021-09-30T12:30:00.000Z",
    ido_distributed_at: "2021-09-30T12:30:00.000Z",
    prospect_usd_token_price: 0.0,
    prospect_initial_market_cap: 0.0,
    prospect_initial_token_circulation: 0.0,
    token_symbol: "ORION",
    ido_readiness_state: "ready",
    pool_contracts_available: true,
    // pool_contract_address: "0x2be1C2E4aF39b335f15c3E682683156664EAb2Dd",
    pool_contract_address: "0x40FD21F9949C2DC17F74D422d34699339615cd41",
    pool_chain: "ethereum",
    finalized: true,
    applications_open_at: null,
    applications_close_at: null,
    pool_slug: "orion-money-2",
    pool_progress: 100,
    main_pool_id: 255,
    pool_token_to: "ETH",
    // pool_token_address: "0x2Ec6407504abFe503347e38D5a298D615DBBC0DD",
    // pool_token_address: "0x727f064a78dc734d33eec18d5370aef32ffd46e4",
  },
];
