module.exports = [
  {
    id: 39,
    name: "Mytheria",
    state: "applications_open",
    ido_starts_at: "2021-11-16T13:00:00.000Z",
    min_allocation: null,
    max_allocation: null,
    total_raise: 250000.0,
    cover_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1635936981/projects/mytheria/mytheria-card.jpg",
    logo_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1634914586/projects/mytheria/mytheria-logo.png",
    website_url: "https://mytheria.io/",
    twitter_handle: "@Mytheria_MYRA",
    telegram_handle: "MytheriaGlobal",
    twitter_url: "https://twitter.com/@Mytheria_MYRA",
    telegram_url: "https://t.me/MytheriaGlobal",
    medium_url: "",
    linkedin_url: "",
    discord_url: "",
    github_url: "",
    founded_at: "2021-10-21",
    whitepaper_url:
      "https://v2.mytheria.io/files/Mytheria-Clash-of-Pantheons.pdf",
    description:
      "## Highlights \r\n* Mytheria is a world where Gods from different cultures combat for honor and glory\r\n* It is the first NFT card game that combines play-to-earn and create-to-earn features\r\n* The team has raised $2M in private funding from top-tier VCs\r\n\r\n## Product \r\n### A mythical world with hundreds of characters to choose from\r\nThe game takes place in a world where gods from different cultures combat for honor and glory. Users choose from hundreds of different characters and artifacts to build a deck of cards in order to win battles against other players. Mytheria is the first play-to-earn NFT game that integrates create-to-earn features, where users can do either of the activities to earn cards and game tokens. Mytheria offers players an environment to display their skills in both PvE and PvP, while also keeping them engaged with chances to make practical profits through trading, collecting and the gacha system. \r\n\r\nUsers can start playing the game for free, as all new players receive the starter deck, consisting of 40 individual cards. The battle arena has two lanes and is structured like a MOBA. The player’s mission is to defend their tower and attack the enemy's towers. A game of Mytheria contains a series of rounds and five phases and lasts until victory is achieved. The game is skill-based and is determined by a combination of decision-making during the game as well as by tactically building the deck before the game. \r\n![Mytheria](https://res.cloudinary.com/polkastarter/image/upload/v1634902432/projects/mytheria/mytheria-trident.png)\r\n\r\n## Problem\r\n### Traditional card games don’t allow proper asset ownership.\r\nTraditionally, in-game items are not owned by the players but rather by the companies that create them. When buying an in-game item, like a skin for a character or a card for the deck, players don’t own it – the game publisher merely licenses it to them. Furthermore, many card games in the current crypto market are very similar to each other and lack unique features. Games also fail to incorporate other stakeholders such as artists or creators, which would help to expand the gaming ecosystem and make it more engaging.\r\n\r\n## Solution \r\n### Asset ownership provides endless possibilities to creators and gamers.\r\nMytheria gives players real ownership over the items they purchase or earn in the game, giving them the right to sell an item by participating in a robust and thriving marketplace. Furthermore, instead of reusing old characters over and over again, Mytheria has chosen to allow game artists to bring some fresh creativity into the game. Only in Mytheria, creators have the power to expand the game world as they please. In the so-called GodForge, they can create new skins for Gods and Mortals, Spells or even forge entirely new Gods. Creators can then sell these artworks on the game artist marketplace and even earn a fee from each subsequent trade.\r\n![Mytheria Gods](https://res.cloudinary.com/polkastarter/image/upload/v1634902323/projects/mytheria/mytheria-characters.png) \r\n\r\n## Business Model\r\n### In-game fees and NFT sales as revenue streams.\r\nThe game generates sustainable revenue through several mechanisms such as in-game fees, NFT sales and marketplace transactions.\r\n\r\n## Market \r\n### Main competitors include Gods Unchained, Hearthstone and Splinterland.\r\nGames with similar gameplay to Mytheria have seen tremendous growth in the crypto gaming market. These card games contributed significantly to the increase in the number of players as well as the amount of funds spent on blockchain-based games. More and more traditional gamers are attracted by the elements of NFTs and direct ownership of gaming cards. Mytheria stands out through its unique characters, a new create-to-earn mechanism as well as its tower-defense-style gameplay. \r\n \r\n## Investors  \r\n### $2M raised in private round from top-tier investors.\r\nAmong Mytheria’s investors are Kardia Ventures, Everest Group, Morningstar Ventures, Spark Digital, Bitscale, Polkastarter, Good Games Guild, Youbi Capital, DFG, Master Ventures, Jsquare Group, TKX Capital and Fomocraft Ventures.\r\n\r\n## Team \r\n### Strong expertise in gaming and tech with previous experiences at Dota.\r\n* Le Manh Cuong - CEO \r\n* Ngo Anh Tuan - CGO\r\n* Le Minh Nhat - CMO\r\n* Nghiem Minh Hoang - CFO \r\n\r\n## Token Utility\r\n### MYRA: Mytheria’s native token\r\nMYRA mainly serves four purposes: (1) It is used to reward players for their gameplay and improve retention rates, (2) it is the game's payment currency, with which players purchase assets and buy or upgrade cards, (3) it is used to regulate the play-to-earn economy and protects against bots, (4) and it allows users to participate in governance through proposals and voting. \r\n![MYRA Token](https://res.cloudinary.com/polkastarter/image/upload/v1634902017/projects/mytheria/mytheria-token.png)",
    legal_name: "",
    ethereum: false,
    bsc: true,
    polygon: false,
    application_form_url: null,
    kyc_form_url: "",
    published_at: "2021-10-27T15:10:48.839Z",
    applications_opened_at: "2021-11-01T14:33:45.638Z",
    applications_closed_at: null,
    kyc_opened_at: null,
    kyc_closed_at: null,
    submitted_to_kyc_at: null,
    submitted_to_lottery_at: null,
    contracts_deployed_at: null,
    created_at: "2021-10-21T13:12:43.753Z",
    updated_at: "2021-11-03T10:57:47.402Z",
    permitted_events: ["close_applications"],
    permitted_states: ["applications_closed"],
    slug: "mytheria",
    short_description: "The first Create to Earn NFT blockchain game!",
    ido_ends_at: null,
    ido_distributed_at: null,
    prospect_usd_token_price: 0.135,
    prospect_initial_market_cap: null,
    prospect_initial_token_circulation: null,
    token_symbol: "MYRA",
    ido_readiness_state: "applications_open",
    pool_contracts_available: false,
    pool_contract_address: "0xb27E42e47945BbD329bcFDE155E9E441BBEa20A0",
    pool_chain: "",
    finalized: false,
    applications_open_at: "2021-11-01T15:00:00.000Z",
    applications_close_at: "2021-11-09T14:00:00.000Z",
    pool_slug: "",
    pool_progress: 0,
    main_pool_id: null,
    pool_token_to: "",
    pool_token_address: "0x2Ec6407504abFe503347e38D5a298D615DBBC0DD",
  },

  {
    id: 187,
    name: "Orion Money",
    state: "published",
    ido_starts_at: "2021-09-29T13:00:00.000Z",
    min_allocation: 0.0,
    max_allocation: 0.0,
    total_raise: 400000.0,
    cover_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1632350216/projects/orion-money/orion-cover.png",
    logo_url:
      "https://res.cloudinary.com/polkastarter/image/upload/v1631654327/projects/orion-money/orion-logo.jpg",
    website_url: "https://orion.money/",
    twitter_handle: "@orion_money",
    telegram_handle: "Orion_Money",
    twitter_url: "https://twitter.com/@orion_money",
    telegram_url: "https://t.me/Orion_Money",
    medium_url: "",
    linkedin_url: "",
    discord_url: "",
    github_url: "",
    founded_at: "2021-09-21",
    whitepaper_url:
      "https://orion-money.medium.com/orion-money-litepaper-release-7e98bb3acb6f",
    description:
      "## Highlights\r\n* Orion Money is a service developed to be a place where stablecoin holders can get a safe and secure yield of 20-25% APY in DeFi.\r\n* Orion Money brings high yields from other chains such as Terra to users on Ethereum through an easy decentralized application.\r\n* Orion Money managed to Raise $4.2 million Between seed and community rounds.\r\n\r\n## Product \r\n### Orion Money is a product that provides fixed 13.5% APY on USDT, USDC, DAI, BUSD, as well as 16.5% APY on wUST. \r\nThere are plans to increase this APY to 20-25% in the future after TGE. Additionally, users can make simple deposits, and Orion Money has passed three smart contract audits with amazing results while also managing to provide two insurance plans.",
    legal_name: "",
    ethereum: true,
    bsc: false,
    polygon: false,
    application_form_url: null,
    kyc_form_url: "",
    published_at: "2021-09-20T23:06:51.346Z",
    applications_opened_at: null,
    applications_closed_at: null,
    kyc_opened_at: null,
    kyc_closed_at: null,
    submitted_to_kyc_at: null,
    submitted_to_lottery_at: null,
    contracts_deployed_at: null,
    created_at: "2021-09-20T22:41:59.224Z",
    updated_at: "2021-10-27T20:38:26.413Z",
    permitted_events: ["unpublish"],
    permitted_states: ["draft"],
    slug: "orion-money",
    short_description: "Cross-chain stablecoin bank",
    ido_ends_at: "2021-09-30T12:30:00.000Z",
    ido_distributed_at: "2021-09-30T12:30:00.000Z",
    prospect_usd_token_price: 0.0,
    prospect_initial_market_cap: 0.0,
    prospect_initial_token_circulation: 0.0,
    token_symbol: "ORION",
    ido_readiness_state: "ready",
    pool_contracts_available: true,
    // pool_contract_address: "0x2be1C2E4aF39b335f15c3E682683156664EAb2Dd",
    pool_contract_address: "0xb27E42e47945BbD329bcFDE155E9E441BBEa20A0",
    pool_chain: "ethereum",
    finalized: true,
    applications_open_at: null,
    applications_close_at: null,
    pool_slug: "orion-money-2",
    pool_progress: 100,
    main_pool_id: 255,
    pool_token_to: "ETH",
    pool_token_address: "0x2Ec6407504abFe503347e38D5a298D615DBBC0DD",
    // pool_token_address: "0x727f064a78dc734d33eec18d5370aef32ffd46e4",
  },
];
